export const pipelineData = [
    {
      product: "Pain (Post-Operative)",
      type: "Fixed Dose",
      description: "Pre-filled syringe of local anesthetic formulation for sustained post-surgical pain relief",
      discovery:true,
      preClinical:true,
      phase1:true,
    },
    {
      product: "Oncology (solid tumours)",
      type: "Fixed Dose",
      description: "Pre-filled syringe of anti-neoplastic agent for local management of solid tumours with reduced systemic toxicity",
      discovery:true,
      preClinical:false,
      phase1:false,
    },
    {
      product: "Anti-Infectives (surgical)",
      type: "Fixed Dose",
      description: "Pre-filled syringe of antibiotics for prophylaxis and local management of surgical site infections",
      discovery:true,
      preClinical:false,
      phase1:false,
    },
    {
      product: "Other (incl. Derm)",
      type: "Fixed Dose",
      description: "",
      discovery:true,
      preClinical:false,
      phase1:false,
    },
    {
      product: "Oncology (solid tumours)",
      type: "Fixed Dose Combo",
      description: "Local delivery of multimodal synergistic small molecule and/or monoclonal antibody combinations for solid tumour management with reduced systemic toxicity",
      discovery:true,
      preClinical:false,
      phase1:false,
    },
    {
      product: "Anti-Infectives (surgical)",
      type: "Fixed Dose Combo",
      description: "Pre-filled syringe of synergistic antibiotic combinations for prophylaxis and local management of surgical site infections",
      discovery:true,
      preClinical:false,
      phase1:false,
    },
    {
      product: "Oncology (solid tumours)",
      type: "Smart Materials",
      description: "Locally activated biologic therapy for improved efficacy and reduced systemic toxicity",
      discovery:true,
      preClinical:false,
      phase1:false,
    },
  ]